### ISSUE TITLE
ArgumentException: Two path items have the same signature.  But they do have different paths

### ISSUE THREAD

**Issue by qmarsala-cricut** [yaos/openapi-diff-action#16]
Hello, I am using the global tool yaos.OpenAPI.Diff.CLI.  I hope you don't mind me creating the issue on this repo, I couldn't find the CLI repo to create the issue there.  I am using the tool in a custom github action of mine, however, I started running into the following issue.    System.ArgumentException: Two path items have the same signature: /Products/{}

I am getting this argument exception because I have the following two routes in my controller

[HttpGet("{searchTerm}"] - this is an old deprecated endpoint that we are replacing

[HttpGet] - this is the new one that uses a query string

The paths seem to be different so I believe this argument exception is being thrown incorrectly. 

The generated specs are as follows:

```
"/Products/{searchTerm}": {
      "get": {
        "tags": [
          "Products"
        ],
        "operationId": "GetProductOldAsync",
        "parameters": [
          {
            "name": "searchText",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        },
        "deprecated": true
      }
    },
"/Products": {
      "get": {
        "tags": [
          "Products"
        ],
        "operationId": "GetProductsAsync",
        "parameters": [
          {
            "name": "query",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            }
          },
          {
            "name": "productId",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
```

Any help would be greatly appreciated.  On a side note, I am not able to use this github action (although I would love to!) because we have a custom private nuget feed that would prevent the projects from restoring for build going through this action, which is why I am using your cli version, and my own custom action.

**Comment by fabich** [comment]
hi @qmarsala-cricut 

sorry for the late reply, did not see this issue.
could you send me the whole spec file so I can have a look at it?

**Comment by qmarsala-cricut** [comment]
@fabich Hey, thanks for the reply!  I will get that for you as soon as I can.  I am a bit busy today, we have just disabled our github action for now, and have not yet found a replacement so your help here will be fantastic!

**Comment by fabich** [comment]
hi @qmarsala-cricut 
we are currently working on a new release.
could you send me your spec file so we can include a potential bug fix in this version?

**Comment by qmarsala-cricut** [comment]
@fabich, I will get that to you today, thanks again

**Comment by qmarsala-cricut** [comment]
@fabich Good news!  I don't think you have a bug... I found the conflicting route in our api, we did actually have another router with a path param causing a conflict.  It was just like 5000 lines away from these two so I didn't see it :/  Thanks for taking a look, i'll re open a new issue if I find anything else again.

**Comment by fabich** [comment]
@qmarsala-cricut fyi we open-sourced the underling code here:
https://github.com/LimeFlight/openapi-diff
